import { createClient } from "jsr:@supabase/supabase-js@2";

// ── CORS ─────────────────────────────────────────────────────────────────────
const ALLOWED_ORIGINS = (Deno.env.get("ALLOWED_ORIGINS") ?? "")
  .split(",").map(s => s.trim()).filter(Boolean);

function buildCors(origin: string | null): Record<string, string> {
  const allowed = origin && (ALLOWED_ORIGINS.length === 0 || ALLOWED_ORIGINS.includes(origin))
    ? origin : ALLOWED_ORIGINS[0] ?? "";
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Vary": "Origin",
  };
}

function fail(msg: string, cors: Record<string, string>, status = 400) {
  return new Response(JSON.stringify({ error: msg }), {
    status,
    headers: { "Content-Type": "application/json", ...cors },
  });
}

// ── Minimal Markdown → HTML converter ────────────────────────────────────────
function mdToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br/>")
    .replace(/^(?!<[hHuUlLpP])(.+)$/, "<p>$1</p>");
}

// ── HTML wrapper for PDF-quality output ──────────────────────────────────────
function wrapHtml(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 860px; margin: 40px auto; color: #111; line-height: 1.6; font-size: 15px; }
  h1 { font-size: 26px; font-weight: 800; margin-bottom: 4px; color: #0a0a0a; }
  h2 { font-size: 19px; font-weight: 700; margin-top: 28px; margin-bottom: 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  h3 { font-size: 15px; font-weight: 600; margin-top: 18px; margin-bottom: 4px; }
  p  { margin: 8px 0; }
  ul { margin: 8px 0 8px 20px; }
  li { margin: 3px 0; }
  code { background:#f3f4f6; padding: 1px 5px; border-radius: 4px; font-size: 13px; }
  strong { font-weight: 700; }
  .meta { font-size: 12px; color: #6b7280; margin-bottom: 32px; }
  .brand { font-size: 11px; color: #9ca3af; text-align: right; margin-top: 48px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style>
</head>
<body>
<h1>${title}</h1>
<p class="meta">Generated by Kraitin &nbsp;·&nbsp; ${new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' })}</p>
${body}
<p class="brand">Kraitin — AI-Powered Startup Intelligence &nbsp;·&nbsp; kraitin.com</p>
</body>
</html>`;
}

// ── Simple plain-text → DOCX-like RTF (Word-compatible) ──────────────────────
// We produce an RTF document which Word/LibreOffice opens natively as .docx
function mdToRtf(title: string, md: string): string {
  const escape = (s: string) => s
    .replace(/\\/g, "\\\\").replace(/\{/g, "\\{").replace(/\}/g, "\\}")
    .replace(/[^\x00-\x7F]/g, c => `\\u${c.charCodeAt(0)}?`);

  const lines = md.split("\n").map(line => {
    if (line.startsWith("### ")) return `\\pard\\sb120\\sa60{\\b\\fs22 ${escape(line.slice(4))}}\\par`;
    if (line.startsWith("## "))  return `\\pard\\sb200\\sa80{\\b\\fs26 ${escape(line.slice(3))}}\\par`;
    if (line.startsWith("# "))   return `\\pard\\sb240\\sa100{\\b\\fs32 ${escape(line.slice(2))}}\\par`;
    if (line.startsWith("- "))   return `\\pard\\fi-200\\li400\\sb40 • ${escape(line.slice(2))}\\par`;
    if (line.match(/^\d+\. /))   return `\\pard\\fi-200\\li400\\sb40 ${escape(line)}\\par`;
    if (line.trim() === "")      return `\\pard\\sb60\\par`;
    return `\\pard\\sb60\\sa60 ${escape(line)}\\par`;
  });

  return `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0\\froman\\fcharset0 Times New Roman;}{\\f1\\fswiss\\fcharset0 Arial;}}
{\\info{\\title ${escape(title)}}{\\author Kraitin}}
\\widowctrl\\hyphauto
\\pard\\sb400\\sa120{\\b\\fs40 ${escape(title)}}\\par
\\pard\\sb60\\sa120{\\fs20\\cf1 Generated by Kraitin — ${new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}}\\par
${lines.join("\n")}
}`;
}

// ── Main handler ──────────────────────────────────────────────────────────────
Deno.serve(async (req) => {
  const origin = req.headers.get("origin");
  const cors = buildCors(origin);

  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  if (req.method !== "POST")   return fail("Method not allowed", cors, 405);

  // Auth
  const token = req.headers.get("Authorization")?.replace("Bearer ", "").trim();
  if (!token) return fail("Unauthorized", cors, 401);

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
  const { data: { user }, error: authErr } = await supabase.auth.getUser(token);
  if (authErr || !user) return fail("Unauthorized", cors, 401);

  // Parse
  let reportId: string, format: string;
  try {
    const body = await req.json();
    reportId = body.reportId;
    format   = body.format; // "html" | "rtf"
    if (!reportId || !["html", "rtf"].includes(format)) throw new Error("Invalid params");
  } catch {
    return fail("Invalid request body. Provide reportId and format ('html'|'rtf').", cors, 400);
  }

  // Fetch report (RLS: user can only read their own)
  const { data: report, error: fetchErr } = await supabase
    .from("reports")
    .select("title, content, user_id")
    .eq("id", reportId)
    .eq("user_id", user.id)
    .maybeSingle();

  if (fetchErr || !report) return fail("Report not found or access denied", cors, 404);

  const title = report.title ?? "Kraitin Report";
  const text  = (report.content as Record<string, unknown>)?.text as string ?? "";

  if (format === "html") {
    const html = wrapHtml(title, mdToHtml(text));
    return new Response(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.html"`,
        ...cors,
      },
    });
  }

  // RTF (Word-compatible)
  const rtf = mdToRtf(title, text);
  const enc = new TextEncoder().encode(rtf);
  return new Response(enc, {
    status: 200,
    headers: {
      "Content-Type": "application/rtf",
      "Content-Disposition": `attachment; filename="${title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.rtf"`,
      ...cors,
    },
  });
});
