
INSERT INTO public.opportunities (title, category, description, revenue_estimate, downloads, market_size, growth_percent, competition_score, opportunity_score, growth_velocity, is_hidden_gem, tags) VALUES

-- ── Health & Fitness Apps ──
('Hormone Tracking App for Women', 'Mobile Apps', 'Tracks cycle, mood, energy, and symptoms with AI pattern recognition and personalized insights. Clue has 11M users but lacks AI coaching; 800M women of reproductive age globally underserved.', '$5k–$30k MRR', '5M+/mo', '$4.2B', 82, 46, 90, 'Explosive', true, ARRAY['mobile','health','womens-health','tracking']),
('AI Personal Trainer App', 'Mobile Apps', 'Camera-based form correction, adaptive workout generation, and recovery coaching with no gym required. Peloton app $13/mo; AI coach generates unlimited custom workouts for same price with visual feedback.', '$5k–$30k MRR', '3M+/mo', '$4.8B', 80, 52, 88, 'Rising', false, ARRAY['mobile','fitness','AI','personal-trainer']),
('Walking & Steps Gamification App', 'Mobile Apps', 'Turns daily steps into narrative adventures, streaks, and community challenges. Pokémon GO proved location + gamification works; health-first walking app serves 55+ demographic gap.', '$3k–$18k MRR', '10M+/mo', '$2.8B', 72, 55, 83, 'Rising', false, ARRAY['mobile','fitness','gamification','walking']),
('Intermittent Fasting Tracker', 'Mobile Apps', 'Smart fasting window tracker with metabolic optimization insights and CGM integration. Zero has 5M downloads; AI-driven metabolic coaching layer missing from all current fasting apps.', '$3k–$18k MRR', '8M+/mo', '$2.5B', 74, 55, 83, 'Rising', false, ARRAY['mobile','fasting','health','tracking']),
('Breathwork & HRV Training App', 'Mobile Apps', 'Guided breathing protocols with Apple Watch / Garmin HRV monitoring and stress scoring. Stress costs US employers $300B/yr; 50M+ smartwatch users have HRV hardware but no dedicated app.', '$3k–$18k MRR', '4M+/mo', '$2.2B', 76, 46, 85, 'Rising', true, ARRAY['mobile','breathwork','HRV','stress']),

-- ── Productivity Apps ──
('AI Daily Planner App', 'Mobile Apps', 'Intelligently schedules tasks, meetings, and deep work blocks by priority and energy level. Todoist has 30M users; AI time-blocking that respects cognitive load is the missing layer.', '$4k–$24k MRR', '5M+/mo', '$3.5B', 80, 52, 88, 'Rising', false, ARRAY['mobile','productivity','AI','planning']),
('Focus & Deep Work Timer App', 'Mobile Apps', 'Combines Pomodoro, ambient sound, website blocking, and AI focus coaching in one mobile app. Forest app 5M downloads; unified focus suite with AI adaptation and progress analytics still needed.', '$3k–$18k MRR', '8M+/mo', '$2.2B', 74, 52, 83, 'Rising', false, ARRAY['mobile','focus','deep-work','productivity']),
('AI Meeting Prep & Follow-Up App', 'Mobile Apps', 'Briefs you before every meeting and auto-drafts follow-up emails from calendar context. Professionals attend 23 hours of meetings/week; prep and follow-up account for 30% of meeting waste.', '$4k–$22k MRR', '2M+/mo', '$3.0B', 78, 44, 87, 'Rising', true, ARRAY['mobile','meetings','AI','productivity']),
('Second Brain Note-Taking App', 'Mobile Apps', 'AI-connected notes that surface relevant past ideas during new note creation and research. Obsidian has 1M+ users but requires manual setup; AI-connected graph for non-technical users is open.', '$4k–$24k MRR', '3M+/mo', '$3.2B', 78, 50, 87, 'Rising', true, ARRAY['mobile','notes','second-brain','AI']),
('Screen Time & Digital Wellbeing App', 'Mobile Apps', 'AI-personalized screen time limits with behavioral nudges, not just hard blocks. Apple Screen Time is blunt; parents and professionals need nuanced AI coaching on device habits.', '$3k–$18k MRR', '6M+/mo', '$2.0B', 76, 48, 85, 'Rising', false, ARRAY['mobile','screen-time','digital-wellness','AI']),

-- ── Finance & Money ──
('Split Bills & Group Expense App', 'Mobile Apps', 'Simplifies group trip, dinner, and roommate expense splitting with AI receipt scanning. Splitwise has 50M users but poor UX; AI receipt scanning + instant Venmo/Zelle integration is the upgrade.', '$3k–$18k MRR', '15M+/mo', '$2.8B', 72, 58, 82, 'Rising', false, ARRAY['mobile','finance','expense-splitting','social']),
('Subscription Management & Cancellation App', 'Mobile Apps', 'Tracks all subscriptions, flags unused ones, and cancels them on user''s behalf in one tap. Average American pays for 4.5 forgotten subscriptions totaling $133/mo; app pays for itself immediately.', '$3k–$18k MRR', '10M+/mo', '$2.5B', 78, 52, 87, 'Rising', true, ARRAY['mobile','subscriptions','finance','savings']),
('AI Grocery Budget & Meal Plan App', 'Mobile Apps', 'Plans meals within a budget, generates a shopping list, and tracks nutritional goals simultaneously. Food inflation drove 200% increase in budget cooking apps; AI nutritionist + budget optimizer is the gap.', '$3k–$18k MRR', '8M+/mo', '$2.5B', 76, 50, 85, 'Rising', true, ARRAY['mobile','grocery','meal-planning','budget']),
('Crypto Portfolio Tracker & Alert App', 'Mobile Apps', 'Real-time portfolio tracking with AI-generated market summaries and customizable price alerts. CoinGecko has 10M users; AI narrative layer explaining why prices moved is the missing feature.', '$4k–$22k MRR', '6M+/mo', '$3.2B', 72, 55, 82, 'Rising', false, ARRAY['mobile','crypto','portfolio','tracking']),

-- ── Social & Community ──
('Niche Interest Community App', 'Mobile Apps', 'Builds tight-knit communities around ultra-specific hobbies with meetup coordination. Reddit is too broad; Facebook Groups lack discovery; 10,000+ underserved micro-communities await.', '$4k–$24k MRR', '5M+/mo', '$3.5B', 72, 50, 83, 'Rising', true, ARRAY['mobile','community','social','niche']),
('Anonymous Confession & Support App', 'Mobile Apps', 'Safe, moderated anonymous sharing for mental load, parenting struggles, and work stress. Whisper had 30M users; AI moderation now makes safe anonymous community economically viable.', '$3k–$18k MRR', '8M+/mo', '$2.2B', 70, 46, 82, 'Rising', true, ARRAY['mobile','anonymous','mental-health','community']),
('Local Events Discovery App', 'Mobile Apps', 'Surfaces hyper-local events matching user interests with social RSVP and friend coordination. Eventbrite is for organizers; Meetup is dying; consumers need a TikTok-style local discovery feed.', '$4k–$24k MRR', '10M+/mo', '$3.8B', 74, 50, 85, 'Rising', false, ARRAY['mobile','events','local','discovery']),
('AI Relationship Coach App', 'Mobile Apps', 'Daily check-ins, conflict resolution guidance, and communication exercises for couples. 40% divorce rate in US; 85% of couples who split cite communication as primary issue; AI mediator has scale.', '$3k–$18k MRR', '5M+/mo', '$2.8B', 74, 44, 85, 'Rising', true, ARRAY['mobile','relationships','AI','couples']),

-- ── Travel & Lifestyle ──
('AI Travel Itinerary Builder', 'Mobile Apps', 'Builds complete day-by-day travel plans from a destination and dates, with booking links. TripAdvisor has no itinerary builder; Google Trips shut down; 1.4B international travelers need planning tools.', '$4k–$24k MRR', '5M+/mo', '$4.5B', 80, 50, 88, 'Rising', false, ARRAY['mobile','travel','AI','itinerary']),
('Restaurant Discovery & Review App', 'Mobile Apps', 'AI-personalized restaurant recommendations beyond "trending" based on actual taste preferences. Yelp review manipulation is rampant; 77% of diners distrust reviews; personalization-first approach wins.', '$4k–$22k MRR', '8M+/mo', '$3.5B', 74, 55, 83, 'Rising', false, ARRAY['mobile','restaurants','AI','discovery']),
('AI Packing List & Trip Prep App', 'Mobile Apps', 'Generates personalized packing lists based on destination, weather, activities, and trip length. Travelers forget essentials on 60% of trips; simple AI utility with high daily active use pre-travel.', '$2k–$12k MRR', '6M+/mo', '$1.8B', 70, 46, 82, 'Rising', false, ARRAY['mobile','travel','packing','AI']),
('Digital Nomad Tools App', 'Mobile Apps', 'Combines visa requirements, cost of living, coworking finder, and tax guidance for nomads. 35M digital nomads globally; fragmented tools require 6+ apps; single integrated nomad app needed.', '$4k–$24k MRR', '2M+/mo', '$3.0B', 78, 40, 88, 'Rising', true, ARRAY['mobile','digital-nomad','travel','tools']),
('AI City Guide & Audio Tour App', 'Mobile Apps', 'AI-generated personalized audio tours for any city based on interests, not canned tourist scripts. Rick Steves sells static audio tours; AI generates custom tours for $4 cities in 4 seconds.', '$3k–$18k MRR', '4M+/mo', '$2.5B', 74, 44, 85, 'Rising', true, ARRAY['mobile','travel','audio-guide','AI']),

-- ── Learning & Self-Improvement ──
('Habit Stacking & Behavior Design App', 'Mobile Apps', 'Uses BJ Fogg''s behavior model and AI to design habit routines anchored to existing behaviors. Atomic Habits sold 15M copies proving demand; AI-personalized habit stacking app is the next step.', '$3k–$18k MRR', '5M+/mo', '$2.8B', 76, 50, 85, 'Rising', false, ARRAY['mobile','habits','self-improvement','AI']),
('AI Book Summary & Reading App', 'Mobile Apps', 'AI-curated 10-minute summaries of nonfiction books with key insight extraction. Blinkist has 26M users at $15/mo; AI-native summaries can be generated in real time for any book.', '$4k–$24k MRR', '8M+/mo', '$3.5B', 74, 55, 83, 'Rising', false, ARRAY['mobile','books','summaries','AI']),
('Goal Tracking & Accountability App', 'Mobile Apps', 'Weekly AI check-ins, obstacle coaching, and peer accountability pods for personal goals. Stickk raised $10M; BeReal-style public commitment for goal tracking drives 4x completion rates.', '$3k–$18k MRR', '4M+/mo', '$2.5B', 74, 50, 84, 'Rising', false, ARRAY['mobile','goals','accountability','AI']),
('AI Career Coach App', 'Mobile Apps', 'Resume feedback, interview prep, and salary negotiation coaching via conversational AI. LinkedIn Premium charges $40/mo; AI career coach at $10/mo with real-time practice is the disruption.', '$4k–$24k MRR', '3M+/mo', '$3.5B', 78, 48, 87, 'Rising', false, ARRAY['mobile','career','AI','coaching']),

-- ── Creator & Content ──
('AI Short-Form Video Script Generator', 'Mobile Apps', 'Generates viral TikTok / Reels scripts with hook, body, and CTA optimized per platform. 200M+ creators globally; first-time creators lack scriptwriting skills; AI democratizes content creation.', '$4k–$22k MRR', '10M+/mo', '$4.5B', 84, 52, 89, 'Explosive', false, ARRAY['mobile','creator','video','AI']),
('Photo Editing AI App', 'Mobile Apps', 'One-tap photo enhancement, background removal, and style transfer for casual photographers. Lightroom mobile has 100M users; AI-only editing with no learning curve targets the mainstream.', '$4k–$24k MRR', '20M+/mo', '$3.5B', 80, 60, 85, 'Rising', false, ARRAY['mobile','photo','editing','AI']),
('AI Voiceover & Podcast Mobile Studio', 'Mobile Apps', 'Record, clean, voice-enhance, and publish podcast episodes from a phone in under 10 minutes. 5M active podcasters; 90% record on their phone; professional audio quality from phone mic is the gap.', '$3k–$18k MRR', '2M+/mo', '$2.8B', 76, 46, 85, 'Rising', true, ARRAY['mobile','podcast','voiceover','AI']),
('AI Avatar & Virtual Influencer Creator', 'Mobile Apps', 'Create a photorealistic AI avatar that posts, responds, and builds a social following. Virtual influencer market growing 40% YoY; tools to create them are enterprise-only at $10k+.', '$5k–$30k MRR', '3M+/mo', '$4.0B', 84, 40, 90, 'Explosive', true, ARRAY['mobile','AI-avatar','creator','social']),
('Meme Generator & Trend Reactor App', 'Mobile Apps', 'AI generates relevant memes from trending topics with branded or personal overlay options. 60% of social engagement is meme-based; no dedicated AI meme creator with trend tracking exists.', '$2k–$12k MRR', '15M+/mo', '$1.8B', 72, 52, 81, 'Rising', false, ARRAY['mobile','memes','creator','AI']),

-- ── Games & Entertainment ──
('AI Puzzle Game with Infinite Levels', 'Mobile Apps', 'AI generates unique puzzle levels personalized to player skill, so the game never ends. Mobile puzzle market $6B; AI generation eliminates the level design bottleneck and enables infinite retention.', '$3k–$18k MRR', '20M+/mo', '$6.0B', 76, 58, 85, 'Rising', true, ARRAY['mobile','games','AI','puzzle']),
('Interactive Narrative Story App', 'Mobile Apps', 'Choose-your-own-adventure stories where AI adapts plot to your choices in real time. Episode has 100M users; AI-native narrative removes linear constraints and creates truly unique stories.', '$4k–$24k MRR', '10M+/mo', '$5.5B', 78, 52, 87, 'Rising', true, ARRAY['mobile','games','interactive-fiction','AI']),
('AI Trivia & Quiz Social Game', 'Mobile Apps', 'Real-time multiplayer trivia with AI-generated questions on any topic and live voice chat. HQ Trivia peaked at 2.3M simultaneous users; successor with AI questions and social layers is open.', '$3k–$18k MRR', '8M+/mo', '$2.5B', 72, 50, 82, 'Rising', false, ARRAY['mobile','games','trivia','social']),
('Fantasy Sports AI Advisor App', 'Mobile Apps', 'AI-generated weekly lineup advice, trade analysis, and waiver wire picks for fantasy football. 60M US fantasy sports players spending $10B/yr; AI advisor beats expert picks 68% of the time.', '$4k–$22k MRR', '5M+/mo', '$3.5B', 76, 52, 85, 'Rising', false, ARRAY['mobile','fantasy-sports','AI','sports']),

-- ── Utility & Tools ──
('AI Document Scanner & Organizer', 'Mobile Apps', 'Scans, OCRs, categorizes, and searches any physical document with AI tagging. Adobe Scan has 100M downloads but no AI organization layer; 300M US households drown in paper.', '$3k–$18k MRR', '20M+/mo', '$3.2B', 74, 55, 83, 'Rising', false, ARRAY['mobile','documents','OCR','AI']),
('AI Price Comparison & Deal Finder', 'Mobile Apps', 'Snap a barcode and instantly see the best price across 50 retailers with cashback stacking. Honey was acquired for $4B; mobile-first AI price comparison for in-store shoppers is untapped.', '$4k–$22k MRR', '10M+/mo', '$4.5B', 76, 52, 85, 'Rising', false, ARRAY['mobile','shopping','price-comparison','AI']),
('Smart Home Control Hub App', 'Mobile Apps', 'Universal smart home controller replacing 8+ brand apps with AI scene automation. Average smart home owner uses 5.3 separate apps; unified AI hub is the obvious consumer pain.', '$3k–$18k MRR', '5M+/mo', '$4.0B', 74, 50, 84, 'Rising', false, ARRAY['mobile','smart-home','IoT','AI']),
('AI Plant Care App', 'Mobile Apps', 'Photo-identifies plants, diagnoses diseases, and sends personalized watering reminders. Plant ownership grew 60% post-COVID; 45M US plant owners kill $300 of plants/yr from neglect.', '$2k–$12k MRR', '8M+/mo', '$2.0B', 72, 46, 83, 'Rising', false, ARRAY['mobile','plants','AI','care']),
('AI Pet Health Monitor App', 'Mobile Apps', 'Tracks pet activity, diet, and symptoms with vet telehealth integration for dogs and cats. Pet industry $136B in US; pet owners spend $2B/yr on unnecessary vet visits; AI triage reduces waste.', '$4k–$22k MRR', '6M+/mo', '$3.5B', 76, 46, 86, 'Rising', true, ARRAY['mobile','pets','health','AI']),
('Package & Delivery Tracker Aggregator', 'Mobile Apps', 'Tracks all packages from every carrier in one feed with AI delivery time predictions. 165M US online shoppers track 5+ packages simultaneously across 6 different carrier apps.', '$2k–$12k MRR', '15M+/mo', '$2.2B', 70, 50, 81, 'Rising', false, ARRAY['mobile','delivery','tracking','utility']),
('AI Password Manager & Identity Vault', 'Mobile Apps', 'Biometric-first password manager with AI breach monitoring and dark web alerts. LastPass breach affected 25M users; trust crisis opened market; biometric-first architecture is the answer.', '$3k–$18k MRR', '8M+/mo', '$2.8B', 74, 52, 84, 'Rising', false, ARRAY['mobile','passwords','security','AI']),
('Offline Maps & Navigation App', 'Mobile Apps', 'Full offline navigation with AI route optimization for hiking, road trips, and data-poor regions. Google Maps requires data; 40M+ hikers and travelers in dead zones need offline AI navigation.', '$3k–$18k MRR', '5M+/mo', '$2.5B', 72, 48, 83, 'Rising', false, ARRAY['mobile','maps','offline','navigation']),
('AI Home Maintenance Manager App', 'Mobile Apps', 'Tracks appliance ages, schedules maintenance, and connects to local service providers. Average homeowner spends $3,192/yr on maintenance; 70% of repairs are emergency because of missed upkeep.', '$3k–$18k MRR', '4M+/mo', '$2.8B', 74, 42, 85, 'Rising', true, ARRAY['mobile','home','maintenance','AI']),
('Family Chore & Allowance App', 'Mobile Apps', 'Gamified chore tracking, allowance management, and financial lessons for kids. Greenlight debit card has 6M users; complementary app for chores and rewards taps same household.', '$2k–$12k MRR', '5M+/mo', '$2.0B', 72, 46, 83, 'Rising', false, ARRAY['mobile','family','kids','gamification']),
('AI Recipe Finder from Fridge Photos', 'Mobile Apps', 'Snap your fridge and pantry to get personalized dinner recipes that use what you have. Food waste costs US households $1,500/yr; 60% of people don''t know what to cook with what they own.', '$2k–$12k MRR', '6M+/mo', '$2.2B', 74, 50, 84, 'Rising', true, ARRAY['mobile','food','AI','recipes']);
