
INSERT INTO public.opportunities (title, category, description, revenue_estimate, downloads, market_size, growth_percent, competition_score, opportunity_score, growth_velocity, is_hidden_gem, tags) VALUES

-- ── AI Agents & Automation ──
('Autonomous AI Sales Development Rep', 'AI', 'AI agent that prospects, personalizes outreach, and books meetings without human input. Outreach and Salesloft charge $100+/seat/mo; AI SDR handles 500 prospects/day at $0.10 each.', '$20k–$140k MRR', '5k+/mo', '$8.5B', 92, 35, 95, 'Explosive', true, ARRAY['AI-agents','sales','automation','outbound']),
('AI Legal Contract Review Agent', 'AI', 'Autonomous agent that reviews, redlines, and summarizes contracts in minutes. Law firms charge $400-$800/hr for contract review; AI reduces to $5/contract for SMBs.', '$15k–$100k MRR', '8k+/mo', '$7.2B', 88, 36, 94, 'Explosive', true, ARRAY['AI-agents','legal','contracts','automation']),
('Personal AI Executive Assistant', 'AI', 'Manages inbox, schedules meetings, drafts replies, and summarizes threads autonomously. Superhuman charges $30/mo for speed; AI executive assistant handles full workflow for $20/mo.', '$8k–$50k MRR', '500k+/mo', '$5.5B', 85, 42, 92, 'Explosive', true, ARRAY['AI-agents','productivity','executive','assistant']),
('AI Customer Support Agent Platform', 'AI', 'Fully autonomous Tier-1 support resolving 80% of tickets without human escalation. Intercom charges $74/seat/mo; AI agent handles unlimited volume at fixed monthly cost.', '$18k–$120k MRR', '10k+/mo', '$9.5B', 88, 40, 93, 'Explosive', false, ARRAY['AI-agents','support','automation','customer-service']),
('Multi-Agent AI Research Platform', 'AI', 'Orchestrates 10+ specialized AI agents for deep competitive and market research reports. Perplexity Pro at $20/mo is shallow; enterprise research teams pay $50k+/yr for analyst work.', '$12k–$80k MRR', '20k+/mo', '$6.5B', 86, 38, 93, 'Explosive', true, ARRAY['AI-agents','research','orchestration','enterprise']),
('AI Data Pipeline Automation Agent', 'AI', 'Self-writing ETL pipelines that adapt to schema changes and fix errors autonomously. Fivetran charges $1/credit; AI-native pipeline reduces data engineering time 90%.', '$15k–$100k MRR', '4k+/mo', '$7.8B', 84, 36, 93, 'Explosive', true, ARRAY['AI-agents','data','ETL','engineering']),

-- ── AI Development Tools ──
('AI Code Review & Security Scanner', 'AI', 'Automated PR reviews catching bugs, security vulnerabilities, and style issues before merge. GitHub Copilot writes code; no dominant AI tool reviews it; 2.6B lines of code merged daily on GitHub.', '$8k–$55k MRR', '200k+/mo', '$4.8B', 88, 42, 92, 'Explosive', true, ARRAY['dev-tools','code-review','security','AI']),
('AI Test Generation Platform', 'AI', 'Generates comprehensive unit, integration, and E2E tests from existing code automatically. 40% of developer time on testing; AI-generated tests achieve 95%+ coverage with zero effort.', '$8k–$55k MRR', '150k+/mo', '$4.5B', 85, 40, 92, 'Explosive', true, ARRAY['dev-tools','testing','AI','automation']),
('AI Documentation Generator', 'AI', 'Auto-generates and keeps API docs, inline comments, and wikis in sync with code changes. Companies spend $2B/yr on technical writing; AI reduces doc debt to near-zero.', '$5k–$30k MRR', '250k+/mo', '$3.2B', 82, 44, 89, 'Explosive', true, ARRAY['dev-tools','documentation','AI','developer']),
('AI Database Query Optimizer', 'AI', 'Analyzes slow queries and auto-generates index recommendations and query rewrites. Poor database queries cost $500M+/yr in cloud compute; optimization improves app performance 10x.', '$6k–$40k MRR', '80k+/mo', '$3.8B', 80, 38, 90, 'Rising', true, ARRAY['dev-tools','database','performance','AI']),
('Natural Language to SQL Platform', 'AI', 'Business users query any database in plain English without writing SQL. Mode Analytics raises $30M solving this; 500M Excel users have data but no SQL skills.', '$8k–$55k MRR', '300k+/mo', '$5.2B', 85, 44, 91, 'Explosive', true, ARRAY['dev-tools','SQL','natural-language','analytics']),

-- ── AI for Specific Industries ──
('AI Radiologist Second Opinion Tool', 'AI', 'Deep learning model that reviews X-rays and CT scans alongside radiologists to catch missed findings. FDA-cleared AI radiology growing 55% YoY; radiologist shortage of 30,000 in US by 2030.', '$25k–$180k MRR', '2k+/mo', '$9.5B', 86, 32, 94, 'Explosive', true, ARRAY['AI','healthcare','radiology','diagnostics']),
('AI Financial Advisor for Retail Investors', 'AI', 'Personalized portfolio advice and tax-loss harvesting via conversational AI for non-accredited investors. Robo-advisors are algorithm-only; conversational AI layer drives 5x engagement.', '$5k–$30k MRR', '1M+/mo', '$6.5B', 80, 48, 88, 'Rising', false, ARRAY['AI','finance','investing','advisor']),
('AI Supply Chain Demand Forecasting', 'AI', 'Predicts demand signals 12 weeks ahead using AI across POS data, weather, and social trends. Inventory mis-forecasting costs retailers $1.1T globally; AI reduces error 70% vs statistical models.', '$20k–$150k MRR', '3k+/mo', '$8.5B', 83, 35, 93, 'Explosive', true, ARRAY['AI','supply-chain','forecasting','retail']),
('AI Real Estate Market Analyzer', 'AI', 'Predicts property values and rental yields at address level using satellite, permit, and macro data. Zillow Zestimate has 6.9% error rate; AI-native models achieve 2.1% in trained markets.', '$8k–$55k MRR', '200k+/mo', '$5.5B', 78, 44, 88, 'Rising', false, ARRAY['AI','real-estate','prediction','analytics']),
('AI HR Talent Intelligence Platform', 'AI', 'Identifies high-potential employees, predicts attrition, and generates personalized growth paths. Employee turnover costs $15k average per departure; AI prediction reduces attrition 40%.', '$15k–$100k MRR', '5k+/mo', '$6.8B', 82, 38, 92, 'Explosive', true, ARRAY['AI','HR','talent','prediction']),

-- ── AI Content & Creative ──
('AI Brand Voice Engine', 'AI', 'Learns a company''s tone and generates on-brand copy across all channels from a single prompt. Brand inconsistency costs enterprise companies $10M+/yr; AI maintains perfect voice at scale.', '$8k–$50k MRR', '100k+/mo', '$4.5B', 82, 45, 89, 'Rising', true, ARRAY['AI','content','branding','copywriting']),
('AI Video Script to Production Platform', 'AI', 'Turns a brief into scripted, voice-overed, B-roll video using AI actors and stock footage. Video production averages $3,000/min; AI reduces to $30/min for marketing teams.', '$10k–$65k MRR', '50k+/mo', '$6.2B', 85, 42, 91, 'Explosive', true, ARRAY['AI','video','production','content']),
('AI Podcast Production Suite', 'AI', 'Transcribes, edits, removes filler words, adds chapters and show notes automatically. 5M+ active podcasters; manual editing takes 3 hours per 1-hour episode.', '$4k–$24k MRR', '800k+/mo', '$3.0B', 76, 50, 85, 'Rising', false, ARRAY['AI','podcast','editing','audio']),
('AI Graphic Design for Non-Designers', 'AI', 'Generates print-ready brand assets, social posts, and presentations from text prompts. Canva has 170M users but requires design skill; AI removes the skill barrier entirely.', '$5k–$30k MRR', '3M+/mo', '$5.5B', 80, 58, 86, 'Rising', false, ARRAY['AI','design','graphic','non-designer']),
('AI Localization & Cultural Adaptation Platform', 'AI', 'Translates and culturally adapts marketing content for 50+ markets maintaining brand tone. Machine translation is 70% accurate; cultural adaptation failure costs brands $250M+/yr.', '$12k–$80k MRR', '20k+/mo', '$5.2B', 82, 38, 91, 'Explosive', true, ARRAY['AI','localization','translation','marketing']),

-- ── AI Data & Analytics ──
('AI Business Intelligence Copilot', 'AI', 'Ask any business question in plain English and get charts, trends, and recommendations instantly. Tableau costs $75/user/mo; AI BI eliminates need for analyst expertise across all business users.', '$15k–$100k MRR', '30k+/mo', '$8.5B', 86, 40, 93, 'Explosive', true, ARRAY['AI','BI','analytics','natural-language']),
('AI Anomaly Detection for SaaS Metrics', 'AI', 'Continuously monitors all SaaS KPIs and surfaces anomalies before they become crises. Average SaaS company discovers critical metric drops 72 hours late; AI detection is real-time.', '$8k–$55k MRR', '15k+/mo', '$4.8B', 82, 38, 91, 'Explosive', true, ARRAY['AI','analytics','monitoring','SaaS']),
('AI Competitive Intelligence Monitor', 'AI', 'Tracks competitor pricing, features, reviews, and job postings to surface strategic insights. Klue and Crayon charge $30k+/yr enterprise; SMB-focused AI monitor needed at $200/mo.', '$8k–$55k MRR', '25k+/mo', '$4.5B', 80, 42, 90, 'Rising', true, ARRAY['AI','competitive-intelligence','monitoring','strategy']),
('AI Customer Journey Analytics', 'AI', 'Maps and predicts every touchpoint in the customer lifecycle with actionable intervention triggers. MixPanel and Amplitude charge $25k+/yr; AI layer turns raw events into revenue actions.', '$12k–$80k MRR', '10k+/mo', '$5.8B', 82, 40, 91, 'Explosive', true, ARRAY['AI','analytics','customer-journey','SaaS']),
('AI Churn Prediction Engine', 'AI', 'Predicts which customers will churn 30 days in advance with personalised retention playbooks. SaaS average 5% monthly churn; AI prediction + intervention cuts churn 45% within 90 days.', '$10k–$65k MRR', '8k+/mo', '$4.5B', 82, 38, 91, 'Explosive', true, ARRAY['AI','churn','prediction','SaaS']),

-- ── AI Infrastructure & Platform ──
('AI Model Fine-Tuning Platform for SMBs', 'AI', 'No-code fine-tuning of open-source LLMs on proprietary data with one-click deployment. OpenAI fine-tuning is expensive; Hugging Face too technical; SMBs need a simple middle path.', '$12k–$80k MRR', '15k+/mo', '$6.5B', 86, 38, 92, 'Explosive', true, ARRAY['AI','LLM','fine-tuning','platform']),
('AI Prompt Engineering Studio', 'AI', 'Version-controlled, A/B-tested prompt management platform for teams building LLM products. 500k+ developers building LLM apps; prompt management is the unsexy but critical bottleneck.', '$6k–$40k MRR', '100k+/mo', '$3.5B', 82, 40, 90, 'Explosive', true, ARRAY['AI','prompts','LLM','developer-tools']),
('Vector Database as a Service', 'AI', 'Managed vector search optimized for RAG architectures with automatic chunking and re-ranking. Pinecone at $1B valuation; Weaviate raising heavily; market still fragmented enough for entrants.', '$15k–$100k MRR', '20k+/mo', '$5.5B', 88, 42, 92, 'Explosive', false, ARRAY['AI','vector-db','RAG','infrastructure']),
('AI API Cost Optimization Platform', 'AI', 'Routes LLM calls to the cheapest capable model and caches results to cut AI API spend 60%. Companies spend $100k+/yr on OpenAI APIs; routing intelligence pays for itself in 30 days.', '$8k–$55k MRR', '30k+/mo', '$4.0B', 84, 36, 92, 'Explosive', true, ARRAY['AI','cost-optimization','LLM','API']),
('AI Observability & Hallucination Detection', 'AI', 'Monitors LLM outputs in production for hallucinations, toxicity, and quality regression. Every AI product in production needs output quality monitoring; no dominant tool exists yet.', '$10k–$65k MRR', '15k+/mo', '$4.8B', 86, 36, 93, 'Explosive', true, ARRAY['AI','observability','hallucination','LLM-ops']),

-- ── AI Vertical SaaS ──
('AI Real Estate Listing Copywriter', 'AI', 'Generates MLS-ready property descriptions and social captions from photos and specs in seconds. 5M+ home listings/yr; average agent spends 2 hours per listing on copy.', '$3k–$18k MRR', '500k+/mo', '$2.5B', 74, 48, 84, 'Rising', false, ARRAY['AI','real-estate','copywriting','vertical']),
('AI Restaurant Menu Optimizer', 'AI', 'Analyzes POS data and competitor menus to recommend pricing, descriptions, and item changes. Menu engineering increases restaurant revenue 15-20%; AI democratizes this for 660k+ US restaurants.', '$3k–$18k MRR', '80k+/mo', '$2.2B', 72, 42, 84, 'Rising', true, ARRAY['AI','restaurant','menu','vertical']),
('AI Insurance Claims Processing', 'AI', 'Automates first notice of loss, damage assessment, and settlement calculation from photos. $300B in P&C claims processed annually; manual claims average 23 days; AI resolves in hours.', '$20k–$150k MRR', '2k+/mo', '$9.5B', 82, 34, 93, 'Explosive', true, ARRAY['AI','insurance','claims','automation']),
('AI Recruitment Interview Coach', 'AI', 'Conducts realistic mock interviews, scores answers, and gives personalized feedback for job seekers. 50M+ job seekers/yr; interview coaching charges $500/session; AI democratizes at $20/mo.', '$3k–$20k MRR', '2M+/mo', '$3.5B', 76, 52, 86, 'Rising', false, ARRAY['AI','recruiting','interview','career']),
('AI Meeting Intelligence Platform', 'AI', 'Transcribes, summarizes, and extracts action items from meetings with CRM auto-sync. Gong charges $100/seat/mo targeting enterprise; SMB-focused tool with Zoom/Teams integration needed.', '$8k–$55k MRR', '200k+/mo', '$4.8B', 84, 46, 90, 'Explosive', false, ARRAY['AI','meetings','transcription','CRM']),

-- ── AI Personal & Consumer ──
('AI Personal Finance Coach', 'AI', 'Conversational AI that reviews spending, builds budgets, and coaches toward financial goals weekly. Mint shutdown left 4M users; AI coaching adds behavioral change layer missing from tracker apps.', '$3k–$18k MRR', '5M+/mo', '$4.2B', 76, 52, 85, 'Rising', false, ARRAY['AI','personal-finance','coaching','consumer']),
('AI Language Learning Tutor', 'AI', 'Real-time conversation partner with error correction, pronunciation feedback, and adaptive lessons. Duolingo has 500M users but lacks real conversation; AI tutor fills the production practice gap.', '$4k–$24k MRR', '10M+/mo', '$6.5B', 80, 55, 87, 'Rising', false, ARRAY['AI','language-learning','tutor','consumer']),
('AI Personal Stylist App', 'AI', 'Analyzes wardrobe photos and body type to recommend outfits and shopping decisions. $391B US apparel market; personalized styling services charge $500+/session; AI at $10/mo.', '$3k–$18k MRR', '2M+/mo', '$3.8B', 74, 50, 84, 'Rising', false, ARRAY['AI','fashion','styling','consumer']),
('AI Journaling & Reflection App', 'AI', 'Prompts, responds to, and summarizes personal journal entries with mood trend analysis. Mental health journaling reduces anxiety 40%; AI feedback adds therapeutic layer to solo practice.', '$2k–$12k MRR', '3M+/mo', '$2.8B', 72, 52, 82, 'Rising', false, ARRAY['AI','journaling','mental-health','consumer']),
('AI Home Interior Design Generator', 'AI', 'Generates photorealistic interior redesigns from a phone photo of any room. Houzz charges $59/mo for professionals; AI generates 10 redesigns in 30 seconds for homeowners.', '$4k–$22k MRR', '1.5M+/mo', '$4.5B', 78, 48, 87, 'Rising', true, ARRAY['AI','interior-design','consumer','generative']),

-- ── AI Security & Trust ──
('AI Phishing Detection Platform', 'AI', 'Real-time email and SMS phishing detection for enterprises using LLM-based semantic analysis. 3.4B phishing emails sent daily; signature-based filters miss 40% of novel attacks.', '$15k–$100k MRR', '10k+/mo', '$7.5B', 86, 36, 93, 'Explosive', true, ARRAY['AI','security','phishing','email']),
('AI Deepfake Detection API', 'AI', 'Detects AI-generated faces, voices, and documents in real-time for verification workflows. Deepfake fraud attempts grew 3000% in 2023; identity verification industry needs detection layer.', '$12k–$80k MRR', '8k+/mo', '$5.5B', 88, 34, 94, 'Explosive', true, ARRAY['AI','security','deepfake','detection']),
('AI Compliance Monitoring for Financial Comms', 'AI', 'Monitors all employee communications for regulatory violations in real-time. SEC fines 23 major banks $1.8B for communication compliance failures; AI monitoring prevents violations.', '$20k–$150k MRR', '1k+/mo', '$8.5B', 82, 30, 93, 'Explosive', true, ARRAY['AI','compliance','finance','communications']),

-- ── AI Education & Knowledge ──
('AI Research Paper Summarizer & Connector', 'AI', 'Summarizes any academic paper and surfaces related work, contradictions, and open questions. 50M+ academic papers published; researchers spend 30% of time reading tangentially relevant work.', '$3k–$18k MRR', '1M+/mo', '$3.5B', 78, 44, 87, 'Rising', true, ARRAY['AI','research','academic','knowledge']),
('AI Knowledge Base Builder from Slack', 'AI', 'Converts Slack conversations into structured, searchable documentation automatically. Companies lose $25B/yr to knowledge fragmented in Slack threads; AI extracts and organizes it.', '$8k–$50k MRR', '50k+/mo', '$4.2B', 82, 40, 91, 'Explosive', true, ARRAY['AI','knowledge-base','Slack','documentation']),
('AI Training Data Curation Platform', 'AI', 'Helps ML teams find, clean, and label training datasets 10x faster. Data labeling market $5.4B; model quality bottlenecked by data quality; AI-assisted curation is the unlock.', '$15k–$100k MRR', '5k+/mo', '$5.5B', 84, 36, 92, 'Explosive', true, ARRAY['AI','training-data','ML','labeling']);
