
INSERT INTO public.opportunities (title, category, description, revenue_estimate, downloads, market_size, growth_percent, competition_score, opportunity_score, growth_velocity, is_hidden_gem, tags) VALUES

-- ── Telehealth & Virtual Care ──
('AI Primary Care Platform', 'Health', 'On-demand primary care visits via chat and video with AI pre-triage reducing physician time per consult 60%. Teladoc revenue $2.6B; AI-first approach cuts cost per visit to $15 vs $79 industry average.', '$20k–$150k MRR', '200k+/mo', '$18.5B', 88, 42, 93, 'Explosive', true, ARRAY['telehealth','AI','primary-care','virtual']),
('Mental Health Telehealth for Teens', 'Health', 'On-demand therapy and psychiatry for 13-17 year olds with parental dashboard. Teen mental health crisis drove 200% app download growth since 2020; BetterHelp does not serve under-18.', '$10k–$65k MRR', '150k+/mo', '$6.8B', 85, 40, 92, 'Explosive', true, ARRAY['telehealth','mental-health','teens','therapy']),
('Chronic Disease Remote Monitoring', 'Health', 'Continuous vitals monitoring for diabetes, hypertension, and heart failure patients via wearable + AI. CMS now reimburses RPM at $100+/patient/month; 60M Americans have qualifying conditions.', '$15k–$100k MRR', '80k+/mo', '$12.0B', 82, 38, 92, 'Explosive', true, ARRAY['telehealth','RPM','chronic-disease','wearable']),
('AI Dermatology Triage App', 'Health', 'Photo-based skin condition assessment routing to OTC treatment or derm consult. 50M Americans visit dermatologists annually; 85% of cases could be triaged digitally saving $4.5B.', '$8k–$50k MRR', '300k+/mo', '$5.5B', 78, 44, 88, 'Rising', true, ARRAY['telehealth','dermatology','AI','triage']),
('Second Opinion Telemedicine Platform', 'Health', 'Connect patients with top specialists for second opinions on diagnoses within 48 hours. 12M Americans seek second opinions annually; misdiagnosis costs $100B+ in unnecessary treatment.', '$10k–$65k MRR', '50k+/mo', '$4.5B', 76, 40, 88, 'Rising', true, ARRAY['telehealth','second-opinion','specialist','diagnosis']),
('Pediatric Telehealth for Parents', 'Health', 'On-demand pediatric care via video with AI symptom checker for children 0-12. Parents average 4 urgent pediatric visits/year; 60% happen after-hours when offices are closed.', '$8k–$50k MRR', '400k+/mo', '$5.8B', 80, 42, 89, 'Explosive', false, ARRAY['telehealth','pediatric','parents','AI']),

-- ── Mental Health ──
('AI-Powered CBT Therapy App', 'Health', 'Structured cognitive behavioral therapy delivered by AI with licensed therapist escalation. Woebot raised $90M; clinical evidence shows AI CBT matches therapist outcomes for mild-moderate depression.', '$5k–$30k MRR', '1.5M+/mo', '$8.0B', 78, 52, 87, 'Rising', false, ARRAY['mental-health','CBT','AI','therapy']),
('Burnout Prevention Platform for Clinicians', 'Health', 'Real-time burnout risk scoring and micro-intervention tool for healthcare workers. 60% of physicians report burnout; $17B annual cost to health systems from turnover and errors.', '$12k–$80k MRR', '30k+/mo', '$6.5B', 82, 36, 92, 'Explosive', true, ARRAY['mental-health','burnout','clinicians','B2B']),
('Trauma-Informed Care App', 'Health', 'EMDR-guided self-help app with therapist monitoring portal for PTSD and complex trauma. 70% of adults experience trauma; only 8% receive EMDR despite being gold-standard treatment.', '$4k–$24k MRR', '400k+/mo', '$3.8B', 74, 45, 85, 'Rising', true, ARRAY['mental-health','trauma','EMDR','PTSD']),
('Substance Abuse Recovery App', 'Health', 'Peer accountability, craving journal, and telehealth MAT prescriptions for addiction recovery. 48M Americans have substance use disorder; only 11% receive treatment; digital pathways reduce barriers.', '$6k–$38k MRR', '300k+/mo', '$5.2B', 76, 42, 87, 'Rising', true, ARRAY['mental-health','addiction','recovery','MAT']),
('Corporate Mental Health Benefits Platform', 'Health', 'Employer-sponsored mental health navigation with therapy matching and utilization analytics. 91% of employers now offer EAP; <5% utilization rate signals massive engagement gap.', '$12k–$80k MRR', '25k+/mo', '$7.5B', 80, 44, 89, 'Rising', true, ARRAY['mental-health','corporate','EAP','benefits']),

-- ── Women''s Health ──
('AI Menopause Management Platform', 'Health', 'Symptom tracking, HRT prescriptions, and personalized coaching for perimenopause and menopause. 50M US women in menopause; $600B market largely ignored by mainstream health tech until 2022.', '$12k–$80k MRR', '200k+/mo', '$7.5B', 88, 35, 94, 'Explosive', true, ARRAY['womens-health','menopause','HRT','telehealth']),
('Endometriosis Diagnosis & Management App', 'Health', 'Symptom diary, specialist finder, and AI-guided treatment pathways for endometriosis. 190M women affected globally; average diagnosis takes 7-10 years; no dedicated digital health tool.', '$5k–$30k MRR', '500k+/mo', '$4.2B', 82, 34, 92, 'Explosive', true, ARRAY['womens-health','endometriosis','diagnosis','chronic']),
('Postpartum Mental Health Platform', 'Health', 'Screening, therapy access, and peer support for postpartum depression and anxiety. 1 in 5 new mothers experiences PPD; most cases go undetected; $6B in lost productivity annually.', '$6k–$40k MRR', '300k+/mo', '$4.8B', 78, 38, 90, 'Rising', true, ARRAY['womens-health','postpartum','mental-health','new-moms']),
('Pelvic Floor Health App', 'Health', 'Guided pelvic floor exercises, biofeedback integration, and PT telehealth for incontinence. 25M American women have urinary incontinence; 70% never seek treatment due to stigma.', '$4k–$24k MRR', '600k+/mo', '$3.5B', 76, 36, 89, 'Rising', true, ARRAY['womens-health','pelvic-floor','PT','incontinence']),
('PCOS Management & Fertility App', 'Health', 'Cycle tracking, insulin resistance coaching, and fertility optimization for PCOS patients. 10% of women globally have PCOS; first-line treatment is lifestyle change with no dedicated app.', '$4k–$22k MRR', '800k+/mo', '$3.8B', 76, 42, 87, 'Rising', true, ARRAY['womens-health','PCOS','fertility','hormones']),

-- ── Fitness & Nutrition ──
('AI Sports Injury Prevention Platform', 'Health', 'Movement analysis via phone camera to detect injury risk patterns before they become injuries. ACL tears cost $30k+ to treat; 2M+ sports injuries/yr preventable with early movement screening.', '$6k–$40k MRR', '200k+/mo', '$4.5B', 80, 40, 90, 'Rising', true, ARRAY['fitness','injury-prevention','AI','movement']),
('Clinical-Grade Nutrition Counseling App', 'Health', 'Registered dietitian-supervised meal plans with AI food logging and lab integration. 42% of US adults are obese; medical nutrition therapy reimbursable by insurance since 2022.', '$5k–$30k MRR', '1M+/mo', '$6.2B', 78, 48, 87, 'Rising', false, ARRAY['nutrition','dietitian','obesity','telehealth']),
('Continuous Glucose Monitor Companion App', 'Health', 'AI coaching layer on top of CGM data for non-diabetics optimizing metabolic health. Levels raised $75M; Dexcom G7 available OTC; metabolic optimization market growing 120% YoY.', '$8k–$50k MRR', '400k+/mo', '$5.5B', 92, 45, 93, 'Explosive', false, ARRAY['fitness','CGM','metabolic','AI']),
('Hydration Tracking & Coaching App', 'Health', 'Smart water bottle integration with personalized hydration targets and reminders. 75% of Americans are chronically dehydrated; simple intervention with high engagement potential.', '$2k–$12k MRR', '2M+/mo', '$1.8B', 68, 55, 80, 'Rising', false, ARRAY['fitness','hydration','wellness','tracking']),
('AI Running Coach App', 'Health', 'Adaptive training plans with real-time form coaching via AirPods and smartwatch. 60M US runners; Garmin and Strava lack AI-personalized coaching; injury rate 50% annually.', '$4k–$24k MRR', '1.5M+/mo', '$3.2B', 74, 52, 84, 'Rising', false, ARRAY['fitness','running','AI','coaching']),

-- ── Senior Care ──
('AI Fall Detection & Prevention Platform', 'Health', 'Passive fall detection via ambient sensors with predictive risk scoring and family alerts. Falls cost Medicare $50B annually; 800k hospitalizations/yr; every 11 seconds a senior falls.', '$10k–$65k MRR', '100k+/mo', '$8.5B', 84, 38, 92, 'Explosive', true, ARRAY['senior-care','fall-detection','AI','safety']),
('Dementia Care Coordination Platform', 'Health', 'Family caregiver tools, medication reminders, and professional care team coordination for dementia. 6.7M Americans have Alzheimer; 11M unpaid caregivers need digital support infrastructure.', '$8k–$50k MRR', '150k+/mo', '$6.8B', 80, 40, 91, 'Explosive', true, ARRAY['senior-care','dementia','caregiving','family']),
('Social Isolation Detection for Seniors', 'Health', 'Passive monitoring of daily activity patterns to detect isolation and trigger outreach. Loneliness equivalent to smoking 15 cigarettes/day; 26% of seniors live alone with no digital support.', '$6k–$38k MRR', '80k+/mo', '$4.5B', 78, 36, 90, 'Rising', true, ARRAY['senior-care','isolation','monitoring','AI']),
('Senior Medication Adherence Platform', 'Health', 'Smart pill dispenser + app with caregiver alerts and pharmacist telehealth for seniors. Medication non-adherence causes 125k US deaths annually and $300B in preventable costs.', '$8k–$50k MRR', '120k+/mo', '$5.5B', 80, 40, 90, 'Explosive', true, ARRAY['senior-care','medication','adherence','IoT']),
('Aging-in-Place Technology Platform', 'Health', 'Bundles smart home sensors, telehealth, and emergency response for independent seniors. 90% of seniors want to age at home; average nursing home costs $9,000/month vs $500/month for tech.', '$10k–$65k MRR', '60k+/mo', '$9.0B', 82, 38, 92, 'Explosive', true, ARRAY['senior-care','aging-in-place','smart-home','telehealth']),

-- ── Chronic Disease Management ──
('Diabetes Management Super App', 'Health', 'Unified platform for CGM data, carb counting, insulin logging, and endocrinologist telehealth. 37M US diabetics; fragmented tools average 4 separate apps; one platform reduces burden 70%.', '$10k–$65k MRR', '800k+/mo', '$9.5B', 82, 50, 89, 'Explosive', false, ARRAY['chronic-disease','diabetes','CGM','management']),
('Hypertension Coaching App', 'Health', 'AI-guided lifestyle interventions with blood pressure tracking and cardiologist escalation. 122M US adults have hypertension; only 24% have it under control; $131B annual treatment cost.', '$5k–$30k MRR', '2M+/mo', '$7.5B', 78, 52, 87, 'Rising', false, ARRAY['chronic-disease','hypertension','cardiology','AI']),
('Asthma & Allergy Management Platform', 'Health', 'Inhaler adherence tracking, air quality alerts, and pulmonologist telehealth for asthma patients. 25M US asthma patients; $80B annual cost; 60% of cases preventable with better self-management.', '$5k–$30k MRR', '600k+/mo', '$5.5B', 76, 48, 86, 'Rising', false, ARRAY['chronic-disease','asthma','allergy','adherence']),
('Inflammatory Bowel Disease Tracker', 'Health', 'Symptom diary, food sensitivity tracking, and GI specialist telehealth for Crohn and UC patients. 3M US IBD patients with no dominant digital management app; flare prediction could prevent hospitalizations.', '$4k–$24k MRR', '300k+/mo', '$3.2B', 74, 40, 87, 'Rising', true, ARRAY['chronic-disease','IBD','Crohns','gut']),
('Multiple Sclerosis Symptom Tracker', 'Health', 'Fatigue, cognition, and mobility tracking with neurologist reporting tools for MS patients. 1M US MS patients; disease monitoring currently done via expensive MRIs; digital biomarkers validated.', '$5k–$30k MRR', '200k+/mo', '$3.5B', 74, 38, 88, 'Rising', true, ARRAY['chronic-disease','MS','neurology','tracking']),

-- ── Healthcare Operations & B2B ──
('AI Medical Coding & Billing Automation', 'Health', 'Auto-assigns ICD-10 and CPT codes from clinical notes with 98%+ accuracy. Medical billing errors cost $125B annually; manual coding is 70% of revenue cycle cost for providers.', '$15k–$100k MRR', '5k+/mo', '$10.5B', 84, 38, 93, 'Explosive', true, ARRAY['healthcare-ops','medical-coding','AI','revenue-cycle']),
('Prior Authorization Automation Platform', 'Health', 'AI submits and tracks prior auth requests reducing approval time from days to hours. Prior auth denials cost US healthcare $350B; physicians spend 2+ hours daily on PA paperwork.', '$12k–$80k MRR', '8k+/mo', '$8.5B', 82, 36, 93, 'Explosive', true, ARRAY['healthcare-ops','prior-auth','AI','insurance']),
('Clinical Documentation AI Assistant', 'Health', 'Ambient listening AI transcribes patient encounters directly into structured EHR notes. Physicians spend 50% of time on documentation; Nuance DAX is enterprise-only at $2k+/provider/month.', '$15k–$100k MRR', '10k+/mo', '$9.0B', 86, 40, 93, 'Explosive', true, ARRAY['healthcare-ops','documentation','AI','EHR']),
('Healthcare Staff Scheduling Optimization', 'Health', 'AI-optimized nurse and physician scheduling reducing overtime costs and burnout. US nursing shortage at 200k; poor scheduling causes $9B in overtime annually for health systems.', '$10k–$65k MRR', '3k+/mo', '$6.0B', 78, 40, 89, 'Rising', true, ARRAY['healthcare-ops','scheduling','AI','nursing']),
('Patient Discharge Planning AI', 'Health', 'Predicts readmission risk and automates post-discharge care coordination. 30-day hospital readmissions cost Medicare $26B annually; CMS penalizes hospitals for excess readmissions.', '$12k–$80k MRR', '2k+/mo', '$7.5B', 80, 36, 92, 'Explosive', true, ARRAY['healthcare-ops','discharge','readmission','AI']),
('Dental Practice AI Receptionist', 'Health', 'AI handles appointment booking, insurance verification, and recall campaigns for dental offices. 200k+ US dental practices each spending $80k/yr on front desk staff; 80% routine tasks automatable.', '$4k–$24k MRR', '30k+/mo', '$4.5B', 76, 42, 87, 'Rising', true, ARRAY['healthcare-ops','dental','AI','scheduling']),

-- ── Preventive & Precision Health ──
('Whole Genome Sequencing Consumer Platform', 'Health', 'Affordable WGS with AI-powered health risk reports and ongoing variant updates. 23andMe proved mass demand at $199; WGS cost now below $200; 10x more data than SNP arrays.', '$8k–$50k MRR', '100k+/mo', '$7.5B', 82, 45, 89, 'Explosive', true, ARRAY['precision-health','genomics','WGS','prevention']),
('Biological Age Testing Platform', 'Health', 'At-home epigenetic methylation tests to measure true biological age vs chronological age. Bryan Johnson Blueprint went viral; biological age testing market growing 200% YoY from near zero.', '$6k–$40k MRR', '200k+/mo', '$4.5B', 95, 38, 94, 'Explosive', true, ARRAY['precision-health','longevity','epigenetics','biomarkers']),
('Personalized Preventive Health Platform', 'Health', 'Annual blood panel + AI risk stratification + personalized prevention plan. Function Health raised $153M at $1B valuation; $850 annual plan with 100+ biomarkers; market far from saturated.', '$12k–$80k MRR', '80k+/mo', '$8.0B', 84, 40, 92, 'Explosive', true, ARRAY['precision-health','prevention','biomarkers','longevity']),
('Pharmacogenomics Drug Sensitivity App', 'Health', 'Genetic testing to predict which medications will work and which will cause side effects. 7% of US patients have preventable adverse drug reactions; pharmacogenomics 90% accurate predictor.', '$8k–$50k MRR', '50k+/mo', '$5.5B', 80, 38, 91, 'Explosive', true, ARRAY['precision-health','pharmacogenomics','genetics','medication']),
('Microbiome Testing & Coaching Platform', 'Health', 'Gut microbiome analysis with personalized diet and probiotic recommendations. Viome raised $87M; gut-brain axis research validating microbiome interventions for mood and immunity.', '$8k–$50k MRR', '150k+/mo', '$6.2B', 82, 42, 90, 'Explosive', true, ARRAY['precision-health','microbiome','gut-health','personalization']),

-- ── Sleep & Recovery ──
('Clinical Sleep Disorder Platform', 'Health', 'At-home sleep study with AI scoring plus telehealth sleep specialist for insomnia and apnea. 70M Americans have sleep disorders; HST reimbursed by insurance at $300-$900 per study.', '$8k–$50k MRR', '500k+/mo', '$6.5B', 80, 44, 89, 'Rising', true, ARRAY['sleep','sleep-apnea','telehealth','AI']),
('AI Insomnia CBT Program', 'Health', 'Clinically validated digital CBT-I program for chronic insomnia with sleep coach access. CBT-I is first-line insomnia treatment; Sleepio raised $30M; FDA cleared digital therapeutics category growing.', '$4k–$24k MRR', '1M+/mo', '$4.8B', 78, 46, 87, 'Rising', true, ARRAY['sleep','insomnia','CBT-I','digital-therapeutics']),
('Recovery Optimization for Athletes', 'Health', 'HRV, sleep, and readiness scoring with AI coach prescribing training load adjustments. WHOOP at $3.6B valuation; open API ecosystem enables lower-cost coaching layer on existing wearables.', '$5k–$30k MRR', '800k+/mo', '$4.0B', 76, 55, 84, 'Rising', false, ARRAY['sleep','recovery','HRV','athletes']),

-- ── Health Data & AI Infrastructure ──
('Federated Health Data Platform', 'Health', 'HIPAA-compliant data clean room enabling multi-hospital AI model training without data sharing. $68B health AI market needs training data; federated learning resolves privacy barrier.', '$20k–$150k MRR', '500+/mo', '$12.0B', 86, 30, 94, 'Explosive', true, ARRAY['health-data','AI','federated-learning','HIPAA']),
('Real-World Evidence Generation Platform', 'Health', 'Automates RWE study design and analysis from EHR and claims data for pharma companies. FDA increasingly requires RWE; pharma companies spend $2B+/yr on RWE studies manually.', '$25k–$180k MRR', '500+/mo', '$9.5B', 83, 32, 94, 'Explosive', true, ARRAY['health-data','pharma','RWE','AI']),
('Patient-Reported Outcomes Platform', 'Health', 'Automated PRO collection via SMS with AI interpretation for clinical trials and value-based care. FDA requires PROs in 40% of oncology trials; current tools are clunky survey forms.', '$10k–$65k MRR', '2k+/mo', '$5.5B', 78, 36, 90, 'Rising', true, ARRAY['health-data','PRO','clinical-trials','AI']),
('AI Clinical Trial Matching', 'Health', 'Matches patients to eligible clinical trials from EHR data reducing enrollment time 80%. 85% of clinical trials fail to enroll on time costing pharma $600k/day in delays.', '$15k–$100k MRR', '1k+/mo', '$7.0B', 82, 34, 93, 'Explosive', true, ARRAY['health-data','clinical-trials','AI','pharma']),

-- ── Dental & Vision ──
('AI Dental X-Ray Analysis', 'Health', 'Deep learning detection of cavities, bone loss, and pathology in dental radiographs. 200k US dentists take 300M X-rays/yr; AI achieves 95% sensitivity vs 80% for general dentists.', '$8k–$50k MRR', '10k+/mo', '$4.5B', 82, 36, 92, 'Explosive', true, ARRAY['dental','AI','radiology','diagnostics']),
('At-Home Vision Testing App', 'Health', 'Smartphone-based visual acuity and color testing with online eyeglass prescription. 164M Americans wear corrective lenses; 40% skip annual eye exams; CVS Health proved telemedicine model works.', '$4k–$24k MRR', '1M+/mo', '$3.8B', 76, 48, 86, 'Rising', false, ARRAY['vision','eye-care','telehealth','diagnostics']);
