
INSERT INTO public.opportunities (title, category, description, revenue_estimate, downloads, market_size, growth_percent, competition_score, opportunity_score, growth_velocity, is_hidden_gem, tags) VALUES

-- ── K-12 & Tutoring ──
('AI-Powered K-12 Math Tutor', 'Education', 'Adaptive AI tutor that explains concepts, generates practice problems, and adjusts difficulty in real time for grades 3-12. Khan Academy has 140M users but lacks personalized pacing; 50M US K-12 students need it.', '$8k–$50k MRR', '2M+/mo', '$12.0B', 85, 48, 91, 'Explosive', false, ARRAY['K-12','math','AI-tutor','adaptive']),
('AI Essay Writing Coach for High Schoolers', 'Education', 'Teaches essay structure, argument, and revision through guided AI feedback rather than generating text. College Board reports 65% of students lack writing proficiency; AI coach vs AI writer is the ethical differentiator.', '$4k–$24k MRR', '1.5M+/mo', '$4.5B', 80, 46, 88, 'Rising', true, ARRAY['K-12','writing','AI','college-prep']),
('SAT / ACT AI Prep Platform', 'Education', 'Full adaptive diagnostic + personalized study plan + AI tutor targeting each student''s weak areas. Princeton Review charges $1,000+; AI achieves comparable score gains at $20/mo.', '$6k–$38k MRR', '1M+/mo', '$5.5B', 82, 48, 89, 'Rising', false, ARRAY['test-prep','SAT','ACT','AI']),
('Homework Help AI App', 'Education', 'Snap a photo of any homework problem and get step-by-step explanations. Photomath has 220M downloads; AI LLMs now solve multi-subject problems Photomath cannot.', '$5k–$30k MRR', '10M+/mo', '$6.5B', 78, 60, 85, 'Rising', false, ARRAY['K-12','homework','AI','snap-solve']),
('AI Reading Comprehension Coach', 'Education', 'Personalizes reading level, asks Socratic questions, and builds vocabulary through AI conversation. NAEP reports 33% of 4th graders below basic reading; no dominant AI reading intervention exists.', '$5k–$30k MRR', '3M+/mo', '$4.8B', 80, 44, 88, 'Rising', true, ARRAY['K-12','reading','literacy','AI']),
('School District LMS Replacement', 'Education', 'Modern, mobile-first learning management system with AI grading and parent communication. PowerSchool and Schoology are decade-old; 130k US schools need modern infrastructure.', '$12k–$80k MRR', '100k+/mo', '$8.5B', 72, 45, 86, 'Rising', true, ARRAY['K-12','LMS','school','platform']),

-- ── Higher Education ──
('AI College Application Coach', 'Education', 'Personalized college list building, essay feedback, and timeline management for high schoolers. College counselors charge $200-$500/hr; 3.7M college applicants annually need affordable guidance.', '$6k–$40k MRR', '800k+/mo', '$5.2B', 80, 44, 89, 'Rising', true, ARRAY['higher-ed','college-app','AI','counseling']),
('Flashcard & Active Recall Platform with AI', 'Education', 'AI generates optimized flashcard decks from uploaded lecture notes and textbooks. Anki is free but requires manual deck creation; Quizlet has 500M users but lacks AI card generation.', '$4k–$24k MRR', '5M+/mo', '$4.2B', 76, 55, 85, 'Rising', false, ARRAY['higher-ed','flashcards','active-recall','AI']),
('AI Research Assistant for Undergrads', 'Education', 'Helps students find, summarize, and cite academic sources while checking for plagiarism. 20M US college students; avg student spends 6 hrs/week on research; AI compresses to 30 min.', '$3k–$18k MRR', '3M+/mo', '$4.0B', 78, 52, 86, 'Rising', false, ARRAY['higher-ed','research','AI','citations']),
('University AI Advising Chatbot', 'Education', 'Answers degree requirements, financial aid, and registration questions 24/7 for enrolled students. Universities spend $4k per advisor annually; 80% of student questions are repetitive and answerable by AI.', '$8k–$55k MRR', '500k+/mo', '$5.0B', 76, 40, 87, 'Rising', true, ARRAY['higher-ed','advising','chatbot','university']),
('AI-Powered Online Degree Platform', 'Education', 'Accredited micro-credentials and bootcamp certificates with AI learning paths and job placement. Coursera revenue $635M growing 21%; AI-native delivery cuts cost per student 70%.', '$15k–$100k MRR', '400k+/mo', '$9.5B', 82, 48, 89, 'Explosive', false, ARRAY['higher-ed','online-degree','micro-credentials','AI']),

-- ── Professional & Corporate Training ──
('Sales Training AI Roleplay Platform', 'Education', 'AI prospects roleplay realistic objection handling and closing scenarios with scored feedback. Companies spend $2.5B/yr on sales training; 70% forgotten within a week without practice.', '$10k–$65k MRR', '50k+/mo', '$6.5B', 84, 40, 92, 'Explosive', true, ARRAY['professional','sales-training','roleplay','AI']),
('AI Compliance Training Platform', 'Education', 'Personalized, scenario-based compliance training that replaces static annual e-learning modules. $7B compliance training market; 95% of employees call it boring; AI scenarios improve retention 4x.', '$12k–$80k MRR', '30k+/mo', '$7.0B', 82, 38, 92, 'Explosive', true, ARRAY['professional','compliance','training','B2B']),
('Manager Coaching AI Platform', 'Education', 'AI coach that gives real-time guidance on people management, feedback conversations, and conflict. $14B leadership development market; 58% of managers say they received no management training.', '$10k–$65k MRR', '20k+/mo', '$6.5B', 82, 38, 91, 'Explosive', true, ARRAY['professional','manager-coaching','leadership','AI']),
('Technical Skills Upskilling Platform', 'Education', 'AI-curated learning paths for cloud, data, and cybersecurity skills mapped to real job postings. LinkedIn Learning charges $30/mo; AI matches exactly to job requirements, not generic course catalogs.', '$8k–$55k MRR', '500k+/mo', '$8.5B', 84, 48, 90, 'Explosive', false, ARRAY['professional','upskilling','tech','AI']),
('AI Onboarding Acceleration Platform', 'Education', 'Reduces new-hire time-to-productivity from 90 days to 30 days using personalized AI learning paths. Average onboarding costs $4,000 per employee; AI compression saves $3B+ annually for US enterprises.', '$12k–$80k MRR', '15k+/mo', '$5.5B', 80, 36, 91, 'Explosive', true, ARRAY['professional','onboarding','HR','AI']),

-- ── Language & Skills ──
('AI Business English Coaching App', 'Education', 'Teaches professional email writing, presentation skills, and meeting English for non-native speakers. 1.5B English learners globally; business communication gap costs professionals career advancement.', '$4k–$24k MRR', '5M+/mo', '$6.5B', 80, 50, 87, 'Rising', false, ARRAY['language','English','business','AI']),
('Sign Language Learning App', 'Education', 'Camera-based AI recognizes and teaches ASL signs with real-time feedback. 600k deaf Americans; 48M hearing family members; no AI-powered sign language app exists yet.', '$3k–$18k MRR', '800k+/mo', '$1.5B', 74, 32, 88, 'Rising', true, ARRAY['language','ASL','accessibility','AI']),
('AI Debate & Public Speaking Coach', 'Education', 'Records practice speeches, scores delivery, identifies filler words, and suggests improvements. 74% of people have glossophobia; Toastmasters charges $100+/yr; AI coach at $10/mo with instant feedback.', '$3k–$18k MRR', '600k+/mo', '$2.5B', 74, 42, 85, 'Rising', true, ARRAY['skills','public-speaking','AI','coaching']),
('Coding Bootcamp AI Tutor', 'Education', 'Explains code, debugs exercises, and gives real-time hints for bootcamp students and self-learners. 90k+ US coding bootcamp enrollments/yr; 60% drop out due to lack of support; AI reduces drops 40%.', '$4k–$24k MRR', '1M+/mo', '$3.8B', 78, 48, 87, 'Rising', true, ARRAY['skills','coding','bootcamp','AI']),
('AI Music Theory & Instrument Coach', 'Education', 'Listens to practice recordings and gives targeted feedback on pitch, rhythm, and technique. 50M amateur musicians in US; music lessons average $60/hr; AI provides daily feedback at $15/mo.', '$3k–$18k MRR', '1.5M+/mo', '$3.2B', 72, 44, 84, 'Rising', true, ARRAY['skills','music','AI','coaching']),

-- ── Special Needs & Accessibility ──
('AI Dyslexia Reading Support App', 'Education', 'Real-time text reformatting, text-to-speech, and phonics coaching for dyslexic learners. 20% of students have dyslexia; schools provide minimal accommodation; AI fills the daily support gap.', '$4k–$22k MRR', '1M+/mo', '$3.5B', 76, 36, 89, 'Rising', true, ARRAY['accessibility','dyslexia','reading','AI']),
('AI ADHD Study Support Tool', 'Education', 'Break-timed Pomodoro with AI distraction coaching, task chunking, and progress visualization. 6.1M US children have ADHD; 50% don''t use medication; behavioral AI support addresses study failure.', '$3k–$18k MRR', '1.5M+/mo', '$2.8B', 76, 38, 88, 'Rising', true, ARRAY['accessibility','ADHD','focus','AI']),
('AI Speech Therapy App for Kids', 'Education', 'Gamified speech exercises with AI phoneme detection and progress tracking for speech delays. 1 in 12 US children have speech or language disorders; therapist waitlists 6-18 months long.', '$4k–$24k MRR', '600k+/mo', '$2.8B', 78, 34, 90, 'Rising', true, ARRAY['accessibility','speech-therapy','kids','AI']),
('Gifted Education AI Platform', 'Education', 'Accelerated, project-based curriculum for academically gifted K-12 students outside school hours. 3.3M gifted students in US; school curriculum holds them back; no dedicated digital platform.', '$4k–$24k MRR', '400k+/mo', '$2.5B', 74, 36, 87, 'Rising', true, ARRAY['K-12','gifted','advanced-learning','AI']),

-- ── EdTech Infrastructure ──
('AI Grading Assistant for Teachers', 'Education', 'Auto-grades open-ended assignments with rubric alignment and feedback generation. Teachers spend 40% of their time on grading and administrative tasks; AI returns that time to instruction.', '$4k–$24k MRR', '200k+/mo', '$3.8B', 80, 38, 90, 'Rising', true, ARRAY['edtech','grading','AI','teacher-tools']),
('Student Engagement Analytics Platform', 'Education', 'Identifies at-risk students using attendance, grades, and engagement signals before they fail. 40% of US college students don''t complete their degree; early warning systems improve graduation 25%.', '$8k–$55k MRR', '50k+/mo', '$4.5B', 78, 38, 89, 'Rising', true, ARRAY['edtech','analytics','at-risk','retention']),
('AI Parent-Teacher Communication Platform', 'Education', 'Translates teacher updates into 50+ languages and surfaces key information for busy parents. 22% of US students come from non-English-speaking households; communication gap damages outcomes.', '$4k–$24k MRR', '300k+/mo', '$2.8B', 76, 38, 87, 'Rising', true, ARRAY['edtech','parent-engagement','translation','AI']),
('Micro-Learning Mobile App for Professionals', 'Education', '5-minute daily lessons covering business, finance, and leadership for career growth on commutes. Headway app 10M downloads at $60/yr; AI-curated lessons mapped to career goals needed.', '$4k–$24k MRR', '5M+/mo', '$4.5B', 76, 52, 85, 'Rising', false, ARRAY['edtech','micro-learning','mobile','professional']),
('Virtual Science Lab Platform', 'Education', 'Photorealistic 3D simulations of chemistry, physics, and biology experiments for K-12 and college. Lab supplies cost schools $50/student/yr; virtual labs 90% cheaper with better safety outcomes.', '$6k–$38k MRR', '500k+/mo', '$4.0B', 74, 40, 86, 'Rising', true, ARRAY['edtech','virtual-lab','STEM','simulation']),

-- ── Early Childhood ──
('AI Early Literacy App for Ages 3-6', 'Education', 'Adaptive phonics, letter recognition, and storytelling for pre-K through kindergarten. 3.7M US kindergartners; reading readiness gap by age 5 predicts academic trajectory for life.', '$3k–$18k MRR', '2M+/mo', '$3.5B', 78, 46, 87, 'Rising', true, ARRAY['early-childhood','literacy','AI','pre-K']),
('STEM Toy + App Learning Platform', 'Education', 'Physical coding and robotics kits paired with gamified AI app curriculum for ages 6-12. LEGO Education revenue $800M; AI app layer adds adaptive curriculum missing from kit-only products.', '$5k–$30k MRR', '500k+/mo', '$5.5B', 76, 50, 85, 'Rising', false, ARRAY['early-childhood','STEM','robotics','coding']),
('AI Bedtime Story Generator for Parents', 'Education', 'Generates personalized, educational bedtime stories featuring the child as hero, teaching core concepts. 37M US households with children under 10; bedtime routine is the #1 engagement moment.', '$2k–$12k MRR', '3M+/mo', '$2.5B', 72, 46, 83, 'Rising', false, ARRAY['early-childhood','storytelling','AI','parents']),

-- ── Exam & Certification ──
('CPA Exam AI Prep Platform', 'Education', 'Adaptive practice exams with AI explanation of wrong answers for all 4 CPA exam sections. 72k US CPA exam candidates annually; Becker charges $3,500; AI delivers comparable pass rates at $200.', '$6k–$40k MRR', '200k+/mo', '$3.0B', 76, 42, 87, 'Rising', true, ARRAY['certification','CPA','exam-prep','AI']),
('USMLE Step 1/2/3 AI Tutor', 'Education', 'Medical board exam prep with AI question explanation and spaced repetition. 20k+ US medical students sit USMLE annually; Amboss charges $300/yr; AI tutoring at same cost with better personalization.', '$8k–$50k MRR', '100k+/mo', '$3.5B', 78, 44, 88, 'Rising', true, ARRAY['certification','USMLE','medical','AI']),
('Bar Exam AI Prep Platform', 'Education', 'Multistate and essay AI tutoring for law school graduates preparing for the bar. 68k bar exam takers annually; Themis and Kaplan charge $3,000+; AI halves cost with better adaptive practice.', '$6k–$40k MRR', '150k+/mo', '$2.8B', 74, 42, 86, 'Rising', true, ARRAY['certification','bar-exam','legal','AI']),
('Cybersecurity Certification Lab', 'Education', 'Hands-on cloud lab environment for CompTIA, CEH, and CISSP certification practice. Cybersecurity has 750k US job openings; TryHackMe has 2M users; enterprise lab platform still open.', '$8k–$55k MRR', '300k+/mo', '$4.5B', 82, 44, 90, 'Explosive', true, ARRAY['certification','cybersecurity','lab','cloud']),
('PMP Project Management AI Coach', 'Education', 'Adaptive exam prep and real-world scenario coaching for Project Management Professional certification. 1.2M PMP holders; PMI expects 22M new PM roles by 2027; only static prep courses exist.', '$4k–$24k MRR', '400k+/mo', '$2.5B', 74, 46, 84, 'Rising', false, ARRAY['certification','PMP','project-management','AI']),

-- ── Tutoring Marketplace ──
('AI-Matched Live Tutoring Marketplace', 'Education', 'Matches students to human tutors using AI assessment of gaps, learning style, and tutor track record. Wyzant and Varsity Tutors are generic; AI matching improves outcomes 35% vs random assignment.', '$8k–$55k MRR', '500k+/mo', '$6.5B', 76, 50, 86, 'Rising', false, ARRAY['marketplace','tutoring','AI','matching']),
('Group Study AI Facilitator', 'Education', 'AI joins virtual study groups to guide discussion, answer questions, and keep groups on track. Zoom fatigue reduced peer study 40%; AI facilitator maintains productivity and accountability.', '$3k–$18k MRR', '1M+/mo', '$2.5B', 74, 44, 84, 'Rising', true, ARRAY['marketplace','group-study','AI','collaboration']),
('Teacher Creator Marketplace', 'Education', 'Platform for teachers to sell AI-generated lesson plans, worksheets, and curricula. Teachers Pay Teachers $500M revenue; AI tools let one teacher produce 100x more content at higher quality.', '$5k–$30k MRR', '400k+/mo', '$4.0B', 78, 46, 87, 'Rising', true, ARRAY['marketplace','teachers','creator','curriculum']),
('University Research Collaboration Platform', 'Education', 'Connects PhD students and professors across universities for interdisciplinary collaboration. $85B in US university R&D; collaboration tools are email and Google Docs; dedicated platform needed.', '$8k–$55k MRR', '100k+/mo', '$3.5B', 72, 36, 86, 'Rising', true, ARRAY['higher-ed','research','collaboration','platform']),

-- ── Emerging Ed Models ──
('Homeschool AI Curriculum Platform', 'Education', 'Full K-12 AI-adaptive curriculum for the 4M US homeschooled students with parent dashboard. Homeschool enrollment grew 75% post-COVID; no comprehensive AI curriculum platform serves this market.', '$6k–$40k MRR', '800k+/mo', '$5.5B', 84, 38, 91, 'Explosive', true, ARRAY['homeschool','AI','curriculum','K-12']),
('AI Financial Literacy App for Teens', 'Education', 'Teaches budgeting, investing, and credit through gamified simulations for ages 13-18. Only 57% of US states require financial literacy in school; 40M teens need this outside classroom.', '$3k–$18k MRR', '2M+/mo', '$3.0B', 78, 42, 87, 'Rising', true, ARRAY['financial-literacy','teens','AI','gamification']),
('AI Study Abroad & International Education Matcher', 'Education', 'Matches students to international programs, scholarships, and visa requirements using AI. 340k US students study abroad annually; complex matching currently done by expensive agencies.', '$4k–$24k MRR', '300k+/mo', '$2.5B', 70, 36, 84, 'Rising', true, ARRAY['higher-ed','study-abroad','matching','AI']),
('AI Lesson Plan Generator for Teachers', 'Education', 'Generates standards-aligned, differentiated lesson plans in 60 seconds from a topic and grade level. Teachers spend 12 hours/week on planning; AI automates 80% of that to reclaim instruction time.', '$3k–$18k MRR', '1M+/mo', '$3.5B', 82, 44, 89, 'Rising', true, ARRAY['edtech','lesson-plans','AI','teacher-tools']),
('VR Immersive History & Geography Learning', 'Education', 'Walk through ancient Rome or the Amazon via VR for K-12 history and geography classes. Meta Quest 3 costs $500; school device pools growing; immersive learning improves retention 75%.', '$6k–$40k MRR', '200k+/mo', '$4.2B', 76, 38, 87, 'Rising', true, ARRAY['edtech','VR','history','immersive']);
