
INSERT INTO public.opportunities (title, category, description, revenue_estimate, downloads, market_size, growth_percent, competition_score, opportunity_score, growth_velocity, is_hidden_gem, tags) VALUES

-- ── AI Writing & Communication ──
('AI Email Triage & Drafting Tool', 'Productivity', 'Categorizes, prioritizes, and drafts replies for inboxes processing 100+ emails/day. Knowledge workers spend 28% of workday on email; AI inbox management returns 2 hours daily.', '$6k–$40k MRR', '1M+/mo', '$5.5B', 84, 46, 91, 'Explosive', true, ARRAY['productivity','email','AI','writing']),
('AI Slack Message Summarizer', 'Productivity', 'Summarizes unread Slack threads and channels into a 2-minute morning briefing. Average professional loses 72 minutes/day to Slack; summary digest restores deep work time.', '$5k–$30k MRR', '500k+/mo', '$3.5B', 82, 42, 90, 'Explosive', true, ARRAY['productivity','Slack','AI','async']),
('AI Report & Memo Generator', 'Productivity', 'Transforms bullet points and data into polished business reports, memos, and summaries. Executives spend 23% of time writing reports; AI compresses 3 hours to 15 minutes per document.', '$6k–$38k MRR', '300k+/mo', '$4.2B', 80, 44, 89, 'Rising', false, ARRAY['productivity','writing','AI','reports']),
('AI Meeting Summarizer & Action Item Extractor', 'Productivity', 'Auto-generates meeting summaries and assigns action items with deadlines from recorded meetings. $37B wasted annually on unproductive meetings; action item tracking reduces follow-through failures 60%.', '$6k–$40k MRR', '800k+/mo', '$4.8B', 82, 46, 90, 'Explosive', false, ARRAY['productivity','meetings','AI','summaries']),
('AI Proposal & Pitch Deck Generator', 'Productivity', 'Builds client proposals and pitch decks from a brief in 5 minutes with brand-consistent design. Agencies and consultants spend 8 hours per proposal; AI reduces to 30 minutes with higher conversion.', '$8k–$55k MRR', '200k+/mo', '$4.5B', 82, 42, 91, 'Explosive', true, ARRAY['productivity','proposals','AI','sales']),
('Voice-to-Structured-Notes App', 'Productivity', 'Speaks thoughts aloud; AI transcribes and organizes into tagged, searchable structured notes. Physicians, lawyers, and consultants need hands-free capture; existing voice tools output unstructured text.', '$4k–$24k MRR', '400k+/mo', '$3.2B', 80, 40, 90, 'Rising', true, ARRAY['productivity','voice','notes','AI']),

-- ── Project & Task Management ──
('AI Sprint Planning Assistant', 'Productivity', 'Reviews backlog, estimates stories, and suggests sprint compositions based on team velocity. Jira overwhelms solo teams; Linear is clean but not AI-powered; sprint AI is the missing layer.', '$6k–$40k MRR', '150k+/mo', '$4.5B', 80, 42, 90, 'Rising', true, ARRAY['productivity','sprint','AI','project-management']),
('AI OKR Management Platform', 'Productivity', 'Helps teams set measurable OKRs, tracks progress, and surfaces blockers automatically. 70% of companies fail to execute strategy due to poor OKR visibility; AI keeps alignment in real time.', '$8k–$55k MRR', '100k+/mo', '$4.8B', 78, 40, 89, 'Rising', true, ARRAY['productivity','OKR','strategy','AI']),
('Personal Task AI Prioritizer', 'Productivity', 'Scores and reorders your task list by urgency, importance, and energy level each morning. 83% of people feel their to-do list is out of control; AI priority scoring restores clarity.', '$3k–$18k MRR', '2M+/mo', '$3.0B', 78, 52, 86, 'Rising', false, ARRAY['productivity','tasks','AI','prioritization']),
('Team Async Status Update Tool', 'Productivity', 'Daily async standup where AI synthesizes team updates and flags blockers for managers. Remote teams waste 45 min/day on status meetings; async AI standup replaces sync overhead.', '$5k–$30k MRR', '200k+/mo', '$3.5B', 78, 42, 88, 'Rising', true, ARRAY['productivity','async','standup','remote']),
('Cross-App Task Aggregator', 'Productivity', 'Pulls tasks from Jira, GitHub, Notion, and email into one AI-prioritized daily view. Average knowledge worker has tasks in 5+ tools; aggregation with AI priority cuts tool-switching 80%.', '$4k–$24k MRR', '600k+/mo', '$3.8B', 80, 44, 89, 'Rising', true, ARRAY['productivity','tasks','integration','AI']),

-- ── Knowledge & Research ──
('AI-Powered Wiki Builder for Teams', 'Productivity', 'Converts Slack, email, and docs into a self-maintaining team knowledge base. Confluence has $2B revenue but requires manual maintenance; AI self-populating wiki is the leap.', '$8k–$55k MRR', '100k+/mo', '$5.5B', 80, 42, 90, 'Explosive', true, ARRAY['productivity','wiki','knowledge','AI']),
('AI Web Research Assistant', 'Productivity', 'Researches any topic across the web and returns structured, sourced summaries in seconds. Knowledge workers spend 19% of time searching for information; AI compresses to near-zero.', '$5k–$30k MRR', '1M+/mo', '$4.2B', 82, 46, 89, 'Rising', false, ARRAY['productivity','research','AI','web']),
('PDF & Document Chat Tool', 'Productivity', 'Chat with any PDF, report, or contract to extract answers without reading it. Lawyers, researchers, and consultants read 100+ pages daily; AI Q&A compresses to 5 minutes.', '$5k–$30k MRR', '800k+/mo', '$3.8B', 82, 48, 88, 'Rising', false, ARRAY['productivity','PDF','AI','documents']),
('AI Competitive Analysis Builder', 'Productivity', 'Automatically generates competitor teardowns from a URL input with positioning and SWOT. Founders spend 10+ hours on competitive analysis before each board deck; AI completes in 10 minutes.', '$6k–$40k MRR', '200k+/mo', '$3.5B', 80, 40, 90, 'Rising', true, ARRAY['productivity','competitive-analysis','AI','strategy']),
('Personal AI Knowledge Graph', 'Productivity', 'Connects notes, bookmarks, emails, and documents into a queryable personal knowledge base. Roam Research has 200k power users; AI-automated linking removes the manual tagging barrier.', '$4k–$24k MRR', '500k+/mo', '$3.2B', 78, 44, 87, 'Rising', true, ARRAY['productivity','knowledge-graph','AI','notes']),

-- ── Calendar & Time ──
('AI Calendar Optimization Tool', 'Productivity', 'Analyzes calendar fragmentation and automatically creates deep work blocks, recovery time, and meeting clusters. Average executive has 27 scheduled meetings/week with no deep work; AI redesigns the week.', '$5k–$30k MRR', '500k+/mo', '$3.8B', 80, 44, 89, 'Rising', true, ARRAY['productivity','calendar','AI','time-management']),
('Smart Scheduling Link Tool', 'Productivity', 'Context-aware scheduling that proposes optimal times based on energy, timezone, and meeting type. Calendly has $3B valuation; AI-native scheduling that optimizes for cognitive performance is the next.', '$4k–$24k MRR', '1M+/mo', '$3.5B', 78, 52, 86, 'Rising', false, ARRAY['productivity','scheduling','AI','calendar']),
('Time Tracking & Billing AI', 'Productivity', 'Passive AI time tracker that categorizes work automatically without manual timers. Toggl has 5M users; 40% of billable hours go untracked in professional services; AI captures the gap.', '$4k–$24k MRR', '600k+/mo', '$3.2B', 76, 48, 86, 'Rising', false, ARRAY['productivity','time-tracking','billing','AI']),
('AI Work Journal & Reflection Tool', 'Productivity', 'Daily 5-minute AI-prompted work journal that identifies patterns, wins, and blockers over time. High performers journal; 95% stop due to consistency; AI prompts and weekly insights sustain the habit.', '$2k–$12k MRR', '1M+/mo', '$2.2B', 74, 44, 84, 'Rising', false, ARRAY['productivity','journaling','reflection','AI']),

-- ── Automation & Integration ──
('No-Code Workflow Automation Platform', 'Productivity', 'Drag-and-drop automation builder for SaaS tools without Zapier''s complexity and pricing. Zapier processes $140M ARR but 78% of users abandon setups due to complexity; simpler AI-guided builder wins.', '$8k–$55k MRR', '200k+/mo', '$6.5B', 82, 48, 89, 'Explosive', false, ARRAY['productivity','automation','no-code','workflow']),
('AI SOP Generator & Documenter', 'Productivity', 'Watches how work is done and generates standard operating procedures automatically. Businesses spend $46B/yr on process documentation; AI generation from screen recording is 100x faster.', '$6k–$40k MRR', '100k+/mo', '$4.5B', 80, 36, 91, 'Explosive', true, ARRAY['productivity','SOPs','documentation','AI']),
('Browser AI Co-pilot Extension', 'Productivity', 'Lives in the browser to summarize pages, draft emails, fill forms, and answer questions in context. Arc Browser has 1M users; AI co-pilot layer for any website is the power user differentiator.', '$4k–$24k MRR', '3M+/mo', '$4.8B', 84, 48, 90, 'Explosive', false, ARRAY['productivity','browser','AI','extension']),
('AI Clipboard & Snippets Manager', 'Productivity', 'Intelligent clipboard that learns frequently pasted content, tags it, and surfaces it contextually. TextExpander has 100k users; AI that learns your patterns without manual setup is the leap.', '$3k–$18k MRR', '800k+/mo', '$2.2B', 74, 44, 84, 'Rising', true, ARRAY['productivity','clipboard','snippets','AI']),
('AI Form & Data Entry Automator', 'Productivity', 'Fills web forms and repetitive data entry tasks from a personal data profile automatically. Workers spend 4.5 hours/week on data entry; AI automation reclaims that time immediately.', '$4k–$24k MRR', '500k+/mo', '$3.5B', 78, 42, 88, 'Rising', true, ARRAY['productivity','automation','forms','AI']),

-- ── Collaboration & Remote Work ──
('AI Team Retrospective Facilitator', 'Productivity', 'Generates retro prompts, synthesizes responses, and tracks action items across sprints. 73% of remote teams say retros are the meeting they skip most; AI facilitation makes them valuable.', '$4k–$24k MRR', '100k+/mo', '$2.8B', 76, 38, 87, 'Rising', true, ARRAY['productivity','retrospective','agile','AI']),
('Async Video Update Tool', 'Productivity', 'Record 2-minute screen walkthroughs with AI transcription, chapters, and Q&A for remote teams. Loom raised $350M; AI-native features that Loom lacks: auto-editing, transcription, and Q&A.', '$5k–$30k MRR', '400k+/mo', '$3.5B', 78, 48, 87, 'Rising', false, ARRAY['productivity','async','video','remote']),
('AI Document Co-authoring Tool', 'Productivity', 'Real-time AI writing assistant embedded in collaborative docs with style consistency checking. Google Docs has 1B users; AI co-author that maintains voice consistency across all contributors is missing.', '$5k–$30k MRR', '1M+/mo', '$4.5B', 80, 50, 87, 'Rising', false, ARRAY['productivity','writing','collaboration','AI']),
('Remote Team Culture & Engagement Platform', 'Productivity', 'AI-facilitated virtual watercooler, team challenges, and pulse surveys for distributed teams. Remote work is permanent for 25% of US jobs; 68% of remote workers feel disconnected from team culture.', '$6k–$40k MRR', '80k+/mo', '$3.8B', 76, 42, 87, 'Rising', true, ARRAY['productivity','remote','culture','engagement']),
('Decision Intelligence Tool', 'Productivity', 'Structures complex decisions with pros/cons frameworks, AI devil''s advocate, and outcome tracking. Leaders make 35k decisions/day; 94% say poor decision process costs them 30% of productivity.', '$5k–$30k MRR', '200k+/mo', '$3.2B', 76, 38, 87, 'Rising', true, ARRAY['productivity','decisions','AI','strategy']),

-- ── Focus & Wellbeing ──
('AI Focus Session Manager', 'Productivity', 'Detects context, blocks distractions, and queues non-urgent notifications during deep work. Context switching costs 23 minutes of focus per interruption; AI protection of deep work time is high ROI.', '$3k–$18k MRR', '2M+/mo', '$2.8B', 78, 50, 86, 'Rising', false, ARRAY['productivity','focus','deep-work','AI']),
('Energy Management & Peak Hours Tracker', 'Productivity', 'Learns your cognitive peak times from calendar behavior and schedules demanding tasks accordingly. Circadian rhythm alignment improves cognitive output 20%; no app maps personal peak hours automatically.', '$3k–$18k MRR', '1M+/mo', '$2.2B', 76, 42, 86, 'Rising', true, ARRAY['productivity','energy','peak-performance','AI']),
('AI Burnout Early Warning System', 'Productivity', 'Monitors work patterns, meeting load, and after-hours activity to flag burnout risk weeks ahead. $300B annual US productivity loss from burnout; early warning gives 4-6 week intervention window.', '$4k–$24k MRR', '500k+/mo', '$3.5B', 78, 38, 89, 'Rising', true, ARRAY['productivity','burnout','wellbeing','AI']),
('Contextual Do Not Disturb Manager', 'Productivity', 'Intelligently manages notification silence based on calendar, location, and current activity. Average person is interrupted 56 times/day; 80% of interruptions are self-rated as unimportant.', '$2k–$12k MRR', '3M+/mo', '$1.8B', 74, 50, 82, 'Rising', false, ARRAY['productivity','notifications','focus','automation']),

-- ── Freelancer & Solo Founder ──
('AI Client Proposal & Invoice Platform', 'Productivity', 'Generates branded proposals, tracks approvals, and creates invoices with one-click payment collection. 59M US freelancers lose $50B/yr to poor client management; AI-native invoicing closes the gap.', '$5k–$30k MRR', '500k+/mo', '$4.5B', 80, 46, 89, 'Rising', true, ARRAY['productivity','freelance','invoicing','AI']),
('Solo Founder OS Dashboard', 'Productivity', 'All-in-one dashboard for solo founders tracking revenue, tasks, customers, and metrics. Solo founders juggle 7+ SaaS tools with no unified view; single-pane-of-glass OS is the solve.', '$4k–$24k MRR', '200k+/mo', '$3.0B', 78, 40, 88, 'Rising', true, ARRAY['productivity','solo-founder','dashboard','tools']),
('AI Contract Generator for Freelancers', 'Productivity', 'Generates legally sound freelance contracts from project scope in 60 seconds. 35M US freelancers use informal agreements; AI contract generation reduces non-payment disputes 70%.', '$3k–$18k MRR', '800k+/mo', '$3.2B', 76, 42, 87, 'Rising', true, ARRAY['productivity','freelance','contracts','AI']),
('Content Calendar & Publishing AI', 'Productivity', 'Plans, writes, schedules, and repurposes social content across all platforms from one interface. Hootsuite has 18M users; AI content generation + repurposing across platforms is the upgrade they lack.', '$5k–$30k MRR', '600k+/mo', '$4.5B', 80, 50, 88, 'Rising', false, ARRAY['productivity','content','social-media','AI']),

-- ── Developer Productivity ──
('AI PR Description Generator', 'Productivity', 'Auto-writes pull request descriptions, changelogs, and release notes from code diffs. Developers dread writing PR descriptions; AI converts code diff to clear description in 5 seconds.', '$4k–$24k MRR', '400k+/mo', '$3.0B', 80, 40, 89, 'Rising', true, ARRAY['productivity','developer','PR','AI']),
('AI Standup Bot for Engineering Teams', 'Productivity', 'Collects async standups via Slack, synthesizes team status, and surfaces blockers for leads. 8M software engineers have daily standups; AI async collection saves 30 min/dev/day.', '$4k–$24k MRR', '200k+/mo', '$2.8B', 78, 40, 88, 'Rising', true, ARRAY['productivity','developer','standup','AI']),
('Smart Tab & Browser Session Manager', 'Productivity', 'AI organizes browser tabs into named sessions, resurfaces relevant tabs by context, and prevents tab overwhelm. 94% of Chrome users have 10+ tabs open; average is 35 tabs; AI session management recovers focus.', '$2k–$12k MRR', '5M+/mo', '$1.8B', 74, 46, 83, 'Rising', false, ARRAY['productivity','browser','tabs','AI']),

-- ── Data & Reporting ──
('AI Weekly Business Report Generator', 'Productivity', 'Connects to Stripe, GA, and CRM to auto-generate weekly business health reports. Founders and managers spend 4 hours/week pulling numbers into reports; AI assembles in 2 minutes.', '$5k–$30k MRR', '200k+/mo', '$4.0B', 80, 38, 90, 'Rising', true, ARRAY['productivity','reporting','AI','analytics']),
('AI Dashboard Builder from Spreadsheets', 'Productivity', 'Converts any Google Sheet or Excel into an interactive dashboard without code. 800M Office users and 900M Google Workspace users manage data in spreadsheets; visualization requires no-code.', '$5k–$30k MRR', '1M+/mo', '$4.5B', 80, 48, 88, 'Rising', false, ARRAY['productivity','dashboards','spreadsheets','no-code']),
('AI Presentation Builder', 'Productivity', 'Turns any doc or bullet points into a polished presentation with branded visuals. Beautiful.ai and Tome raised $175M combined; AI-native slide generation from any content type still open.', '$5k–$30k MRR', '1.5M+/mo', '$4.0B', 80, 52, 87, 'Rising', false, ARRAY['productivity','presentations','AI','design']),
('AI Customer Feedback Synthesizer', 'Productivity', 'Aggregates reviews, support tickets, and NPS responses into weekly insight summaries. Product teams spend 10 hours/week manually categorizing feedback; AI synthesis in 5 minutes.', '$5k–$30k MRR', '80k+/mo', '$3.8B', 78, 38, 90, 'Rising', true, ARRAY['productivity','feedback','AI','product']),
('AI Board Deck & Investor Update Generator', 'Productivity', 'Assembles board deck slides and investor updates from company metrics with narrative framing. Founders spend 3-5 days per quarter on investor decks; AI reduces to half a day with better storytelling.', '$6k–$40k MRR', '30k+/mo', '$3.2B', 78, 34, 90, 'Rising', true, ARRAY['productivity','investor-updates','AI','startups']),
('AI SaaS Metrics Dashboard', 'Productivity', 'Tracks MRR, churn, LTV, CAC, and expansion revenue in real time from Stripe and billing data. Founders use 4 spreadsheets for SaaS metrics; single AI-powered dashboard with anomaly alerts needed.', '$4k–$24k MRR', '50k+/mo', '$3.5B', 80, 40, 90, 'Rising', true, ARRAY['productivity','SaaS-metrics','dashboard','AI']);
